name: "@smakss/uuid"

on:
  release:
    types: [created]

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [16]
    runs-on: ${{ matrix.os }}

  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

  publish-npm:
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          registry-url: https://registry.npmjs.org/
          scope: "@smakss"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          registry-url: https://npm.pkg.github.com/
          scope: "@smakss"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
